site_name: Nominatim Documentation
theme: readthedocs
docs_dir: ${CMAKE_CURRENT_BINARY_DIR}
site_url: https://nominatim.org
repo_url: https://github.com/openstreetmap/Nominatim
pages:
    - 'Introduction' : 'index.md'
    - 'API Reference':
        - 'Overview': 'api/Overview.md'
        - 'Search': 'api/Search.md'
        - 'Reverse': 'api/Reverse.md'
        - 'Address Lookup': 'api/Lookup.md'
        - 'Details' : 'api/Details.md'
        - 'Status' : 'api/Status.md'
        - 'Place Output Formats': 'api/Output.md'
        - 'FAQ': 'api/Faq.md'
    - 'Administration Guide':
        - 'Basic Installation': 'admin/Installation.md'
        - 'Import' : 'admin/Import.md'
        - 'Update' : 'admin/Update.md'
        - 'Deploy' : 'admin/Deployment.md'
        - 'Customize Imports' : 'admin/Customization.md'
        - 'Tokenizers' : 'admin/Tokenizers.md'
        - 'Nominatim UI'  : 'admin/Setup-Nominatim-UI.md'
        - 'Advanced Installations' : 'admin/Advanced-Installations.md'
        - 'Migration from older Versions' : 'admin/Migration.md'
        - 'Troubleshooting' : 'admin/Faq.md'
    - 'Developers Guide':
        - 'Setup for Development' : 'develop/Development-Environment.md'
        - 'Architecture Overview' : 'develop/overview.md'
        - 'OSM Data Import' : 'develop/Import.md'
        - 'Place Ranking' : 'develop/Ranking.md'
        - 'Postcodes' : 'develop/Postcodes.md'
        - 'Testing' : 'develop/Testing.md'
        - 'External Data Sources': 'develop/data-sources.md'
    - 'Appendix':
        - 'Installation on CentOS 7' : 'appendix/Install-on-Centos-7.md'
        - 'Installation on CentOS 8' : 'appendix/Install-on-Centos-8.md'
        - 'Installation on Ubuntu 18' : 'appendix/Install-on-Ubuntu-18.md'
        - 'Installation on Ubuntu 20' : 'appendix/Install-on-Ubuntu-20.md'
markdown_extensions:
    - codehilite
    - admonition
    - toc:
        permalink: 
extra_css: [extra.css, styles.css]
